steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sandbox-286503/ci-cd-go:latest', '-t', 'gcr.io/sandbox-286503/ci-cd-go:$SHORT_SHA', '.']

  - name: 'docker'
    args: ['run', '-d', '--name', 'goapp', 'gcr.io/sandbox-286503/ci-cd-go:latest']

  - name: 'docker'
    args: ['exec', 'goapp', 'go', 'test']
